baseURL = 'https://myblog-gamma-olive.vercel.app/'
title = 'ZJP'
theme = "anatole"
paginate = 8

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[params]
  title = "ZJP's note"
  author = "ZJP"
  # description = "Call me Jane"
  profilePicture = "/static/avatar.jpg"
  description = """
  Sharing knowledge......
  Enjoy yourself
  """

  displayMode = "dark"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
