baseURL = 'https://myblog-gamma-olive.vercel.app/'
title = 'ZJP's Note'
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  #[[menu.main]]
    #identifier = "about"
    #name = "About"
    #url = "\myblog\content\about\about.md"
    #weight = 3

[params]
  author = "ZJPeng"
  description = "Sharing knowledge...."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/mo-xiaoxiu/myblog"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/tkMhJW1bT7Zwof2"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#ffffff"
